# Fusion 360 Add-in (Python)
# Generates propeller blade section sketches from root/mid/tip Selig-format
# airfoil .dat files, creates 3D leading/trailing edge rails, and performs a
# single loft to create a smooth blade body.
#
# UNITS (IMPORTANT):
# - Fusion userParameter.value for LENGTH is returned in Fusion internal units (centimeters),
#   even if the parameter is defined/displayed as inches in the UI.
# - This script works internally in centimeters for all geometry.
#
# Placement:
# - Root station is at X = HubR (absolute)
# - Tip station is at X = Radius (absolute)
#
# Additions included:
# (A) Tip thickness shaping:
#     TipShapeStartS / TipShapeExp / TipThickScale
# (B) Explicit final-station tip chord:
#     stations before the final tip use the ChordRoot/ChordPeak/ChordTip law;
#     only the final station is reduced to FINAL_STATION_CHORD_PREV_FACTOR
#     of the second-to-last chord
# (C) Tip TE-offset:
#     TipTEOffset / TipTEOffsetStartS / TipTEOffsetExp

import adsk.core
import adsk.fusion
import csv
import json
import os
import re
import traceback
import math

CMD_ID = 'cmd_airfoil_sections_selig_dat'
CMD_NAME = 'Generate Airfoil Sections + Rails + Loft (Selig DAT)'
CMD_DESC = 'Creates airfoil sections, LE/TE rails, and lofts a blade body.'

# --- Batch-generation controls ---
# When True, the command asks for variants.csv after the three airfoil .dat files.
# Cancel the CSV dialog to keep the original one-design behavior using the
# current Fusion parameter table.
BATCH_MODE = True
VARIANTS_CSV_NAME = 'variants_pitch_based.csv'
EXPORTS_DIR_NAME = 'exports'
CLEAR_PREVIOUS_BATCH_EXPORTS = True
FIXED_RADIUS_EXPR = "3 in"
TWIST_MODE = "pitch_based"  # Supported values: "linear", "pitch_based"

# --- Geometry/orientation controls ---
BASE_ROT_DEG = 90.0
CENTER_TO_ORIGIN = True
INVERT_TWIST = True

# --- Loft controls ---
MAKE_SOLID_LOFT = True
CREATE_LOFT = True

# --- Single-run speed controls ---
# When BATCH_MODE is False, these preview settings reduce sketch/loft complexity
# so baseline tip/chord iterations run much faster. Batch mode always keeps the
# production-resolution values above.
FAST_SINGLE_RUN_MODE = True
FAST_SINGLE_RUN_AIRFOIL_POINTS = 80
FAST_SINGLE_RUN_MAX_STATIONS = 12
FAST_SINGLE_RUN_SURFACE_LOFT = False

# --- Airfoil blending controls ---
# Leave paths blank to select the root/mid/tip Selig .dat files with file dialogs.
# These defaults use the cambered WFD 16-series airfoils generated by
# make_cambered_16_series.py:
#   root: thickest / hub-friendly
#   mid:  moderate high-speed section
#   tip:  thinnest / tip-friendly section
CAMBERED_AIRFOIL_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'CamberedAirfoils')
RootAirfoilPath = os.path.join(CAMBERED_AIRFOIL_DIR, 'wfd_16-212_root.dat')
MidAirfoilPath = os.path.join(CAMBERED_AIRFOIL_DIR, 'wfd_16-209_mid.dat')
TipAirfoilPath = os.path.join(CAMBERED_AIRFOIL_DIR, 'wfd_16-206_tip.dat')

# s is normalized span: s=0 at HubR, s=1 at Radius.
# In the transition bands, airfoil coordinates are smoothly blended so the
# blade remains one continuous lofted body rather than three abrupt shapes.
ROOT_TO_MID_START_S = 0.20
ROOT_TO_MID_END_S = 0.40
MID_TO_TIP_START_S = 0.65
MID_TO_TIP_END_S = 0.85

# Airfoils from different .dat files often have different point counts. They
# must share the same ordered point count before point-by-point blending.
N_AIRFOIL_POINTS = 160

# Diagnostic option: writes station-specific blended normalized coordinates.
EXPORT_AIRFOIL_DEBUG_CSV = False

# --- Tip chord closure ---
# Keep the normal chord law through the second-to-last station. Only the final
# station is reduced, which avoids hidden tapering from older tip-shaping paths.
FINAL_STATION_CHORD_PREV_FACTOR = 0.35

# --- Root extension / blade count / hub controls ---
ROOT_INBOARD_EXTENSION_IN = 0.30
N_BLADES = 3
HUB_OUTER_DIAMETER_IN = 0.80
HUB_THICKNESS_IN = 0.70
M5_CLEARANCE_HOLE_DIAMETER_MM = 5.2

# Tolerance for identifying LE/TE x locations in normalized airfoil
X_TOL = 1e-5
MIN_TWIST_RADIUS_CM = 1e-6
GENERATED_BLADE_BASE_NAME = 'WFD_Blade'
GENERATED_HUB_BASE_NAME = 'WFD_Hub'
GENERATED_PROP_BASE_NAME = 'WFD_Prop'
IGNORED_CSV_PARAMETER_NAMES = {
    'ChordEnd',
    'TipTaperStartS',
    'TipTaperExp',
    'TipChordScale'
}

_handlers = []

BASE_REQUIRED_PARAMETER_NAMES = [
    'Radius', 'HubR',
    'ChordRoot', 'ChordPeak', 'ChordTip',
    'ChordPeakS',
    'ThickRootScale', 'ThickEndS', 'ThickExp',
    'nStations',

    # Tip thickness shaping:
    'TipShapeStartS', 'TipShapeExp', 'TipThickScale',

    # Tip TE-offset:
    'TipTEOffset', 'TipTEOffsetStartS', 'TipTEOffsetExp'
]


def required_parameter_names():
    names = list(BASE_REQUIRED_PARAMETER_NAMES)
    if TWIST_MODE == "linear":
        names.extend(['TwistRoot', 'TwistTip'])
    elif TWIST_MODE == "pitch_based":
        names.append('GeometricPitch')
    else:
        raise ValueError(
            f'Unsupported TWIST_MODE "{TWIST_MODE}". Use "linear" or "pitch_based".'
        )
    return names


def is_fast_single_run():
    return bool(FAST_SINGLE_RUN_MODE and not BATCH_MODE)


def active_airfoil_point_count():
    if is_fast_single_run():
        return max(20, int(FAST_SINGLE_RUN_AIRFOIL_POINTS))
    return int(N_AIRFOIL_POINTS)


def active_make_solid_loft():
    if is_fast_single_run() and FAST_SINGLE_RUN_SURFACE_LOFT:
        return False
    return bool(MAKE_SOLID_LOFT)


def inch_to_cm(value):
    return float(value) * 2.54


def mm_to_cm(value):
    return float(value) * 0.1


# ---------- Utilities ----------
def get_param(design, name):
    for p in design.userParameters:
        if p.name == name:
            return p
    return None


def require_params(design, names):
    found, missing = {}, []
    for n in names:
        p = get_param(design, n)
        if p:
            found[n] = p
        else:
            missing.append(n)
    return found, missing


def ensure_component(design, name):
    root = design.rootComponent
    if root:
        return root
    raise RuntimeError(
        f'Could not access the root component for generated geometry "{name}".'
    )


def is_generated_body_name(name):
    return (
        name.startswith('BladeBody') or
        name.startswith('BladeLoft') or
        name.startswith(GENERATED_BLADE_BASE_NAME) or
        name.startswith(GENERATED_HUB_BASE_NAME) or
        name.startswith(GENERATED_PROP_BASE_NAME)
    )


def generated_blade_body_name(variant_id=None):
    if variant_id:
        return f'{GENERATED_BLADE_BASE_NAME}_{safe_filename(variant_id)}'
    return GENERATED_BLADE_BASE_NAME


def generated_prop_body_name(variant_id=None):
    if variant_id:
        return f'{GENERATED_PROP_BASE_NAME}_{safe_filename(variant_id)}'
    return GENERATED_PROP_BASE_NAME


def delete_old(comp):
    try:
        for i in reversed(range(comp.features.combineFeatures.count)):
            feat = comp.features.combineFeatures.item(i)
            if feat.name.startswith(GENERATED_PROP_BASE_NAME) or feat.name.startswith(GENERATED_BLADE_BASE_NAME):
                feat.deleteMe()
    except:
        pass
    try:
        for i in reversed(range(comp.features.circularPatternFeatures.count)):
            feat = comp.features.circularPatternFeatures.item(i)
            if feat.name.startswith(GENERATED_BLADE_BASE_NAME):
                feat.deleteMe()
    except:
        pass
    try:
        for i in reversed(range(comp.features.extrudeFeatures.count)):
            feat = comp.features.extrudeFeatures.item(i)
            if feat.name.startswith(GENERATED_HUB_BASE_NAME):
                feat.deleteMe()
    except:
        pass
    # Delete dependent loft features before deleting their input sketches/planes.
    try:
        for i in reversed(range(comp.features.loftFeatures.count)):
            feat = comp.features.loftFeatures.item(i)
            if feat.name.startswith('BladeLoft') or feat.name.startswith(GENERATED_BLADE_BASE_NAME):
                feat.deleteMe()
    except:
        pass
    try:
        for i in reversed(range(comp.bRepBodies.count)):
            body = comp.bRepBodies.item(i)
            if is_generated_body_name(body.name):
                body.deleteMe()
    except:
        pass
    try:
        for i in reversed(range(comp.sketches.count)):
            sk = comp.sketches.item(i)
            if sk.name.startswith('AF_') or sk.name.startswith('Rails_') or sk.name.startswith('Hub_'):
                sk.deleteMe()
    except:
        pass
    try:
        for i in reversed(range(comp.constructionPlanes.count)):
            pl = comp.constructionPlanes.item(i)
            if pl.name.startswith('Plane_s=') or pl.name.startswith('Plane_Hub'):
                pl.deleteMe()
    except:
        pass


def read_selig_dat(path):
    with open(path, 'r') as f:
        lines = [l.strip() for l in f.readlines() if l.strip()]
    name = lines[0]
    pts = []
    for l in lines[1:]:
        try:
            x, y = map(float, l.split())
            pts.append((x, y))
        except:
            pass
    if len(pts) < 20:
        raise ValueError('Invalid or too-short Selig DAT file.')
    return name, pts


def remove_consecutive_duplicate_points(pts, tol=1e-12):
    cleaned = []
    for x, y in pts:
        if not cleaned:
            cleaned.append((x, y))
            continue
        px, py = cleaned[-1]
        if abs(x - px) > tol or abs(y - py) > tol:
            cleaned.append((x, y))
    return cleaned


def resample_airfoil_loop(pts, n_points):
    """
    Resample a Selig-style ordered airfoil curve by arc length.

    The input point order is preserved. We do not sort by x because Selig files
    normally travel TE -> upper -> LE -> lower -> TE, and sorting would destroy
    the section loop needed by Fusion's fitted spline/profile creation.
    """
    if n_points < 3:
        raise ValueError('n_points must be at least 3.')
    pts = remove_consecutive_duplicate_points(pts)
    if len(pts) < 3:
        raise ValueError('Airfoil has too few unique points to resample.')

    cumulative = [0.0]
    for i in range(1, len(pts)):
        x0, y0 = pts[i - 1]
        x1, y1 = pts[i]
        cumulative.append(cumulative[-1] + math.hypot(x1 - x0, y1 - y0))

    total = cumulative[-1]
    if total <= 1e-12:
        raise ValueError('Airfoil arc length is too small to resample.')

    resampled = []
    seg = 1
    for i in range(n_points):
        target = total * i / (n_points - 1)
        while seg < len(cumulative) - 1 and cumulative[seg] < target:
            seg += 1
        d0 = cumulative[seg - 1]
        d1 = cumulative[seg]
        x0, y0 = pts[seg - 1]
        x1, y1 = pts[seg]
        if d1 <= d0:
            t = 0.0
        else:
            t = (target - d0) / (d1 - d0)
        resampled.append((x0 + (x1 - x0) * t, y0 + (y1 - y0) * t))
    return resampled


def blend_airfoils(pts_a, pts_b, weight):
    if len(pts_a) != len(pts_b):
        raise ValueError('Airfoils must have the same point count before blending.')
    w = max(0.0, min(1.0, weight))
    return [
        ((1.0 - w) * ax + w * bx, (1.0 - w) * ay + w * by)
        for (ax, ay), (bx, by) in zip(pts_a, pts_b)
    ]


def validate_airfoil_transition_ranges():
    if active_airfoil_point_count() < 3:
        raise ValueError('Active airfoil point count must be at least 3.')
    if not (0.0 <= ROOT_TO_MID_START_S <= 1.0 and 0.0 <= ROOT_TO_MID_END_S <= 1.0):
        raise ValueError('Root-to-mid transition values must be within [0, 1].')
    if not (0.0 <= MID_TO_TIP_START_S <= 1.0 and 0.0 <= MID_TO_TIP_END_S <= 1.0):
        raise ValueError('Mid-to-tip transition values must be within [0, 1].')
    if not (ROOT_TO_MID_START_S < ROOT_TO_MID_END_S):
        raise ValueError('Invalid airfoil transitions: ROOT_TO_MID_START_S must be < ROOT_TO_MID_END_S.')
    if not (ROOT_TO_MID_END_S <= MID_TO_TIP_START_S):
        raise ValueError('Invalid airfoil transitions: ROOT_TO_MID_END_S must be <= MID_TO_TIP_START_S.')
    if not (MID_TO_TIP_START_S < MID_TO_TIP_END_S):
        raise ValueError('Invalid airfoil transitions: MID_TO_TIP_START_S must be < MID_TO_TIP_END_S.')


def airfoil_for_station(s, root_pts, mid_pts, tip_pts):
    """
    Select or smoothly blend the airfoil for normalized span station s.

    Abrupt airfoil switching can create section discontinuities that make rails
    and lofts kink or fail. Smoothstep eases the root->mid and mid->tip blends
    so adjacent stations evolve gradually.
    """
    if s < ROOT_TO_MID_START_S:
        return root_pts
    if s <= ROOT_TO_MID_END_S:
        denom = ROOT_TO_MID_END_S - ROOT_TO_MID_START_S
        w = smoothstep((s - ROOT_TO_MID_START_S) / denom)
        return blend_airfoils(root_pts, mid_pts, w)
    if s < MID_TO_TIP_START_S:
        return mid_pts
    if s <= MID_TO_TIP_END_S:
        denom = MID_TO_TIP_END_S - MID_TO_TIP_START_S
        w = smoothstep((s - MID_TO_TIP_START_S) / denom)
        return blend_airfoils(mid_pts, tip_pts, w)
    return tip_pts


def airfoil_metadata(airfoil_set):
    return {
        'root_airfoil_filename': os.path.basename(airfoil_set['root_path']),
        'mid_airfoil_filename': os.path.basename(airfoil_set['mid_path']),
        'tip_airfoil_filename': os.path.basename(airfoil_set['tip_path']),
        'root_airfoil_path': airfoil_set['root_path'],
        'mid_airfoil_path': airfoil_set['mid_path'],
        'tip_airfoil_path': airfoil_set['tip_path'],
        'ROOT_TO_MID_START_S': ROOT_TO_MID_START_S,
        'ROOT_TO_MID_END_S': ROOT_TO_MID_END_S,
        'MID_TO_TIP_START_S': MID_TO_TIP_START_S,
        'MID_TO_TIP_END_S': MID_TO_TIP_END_S,
        'N_AIRFOIL_POINTS': active_airfoil_point_count()
    }


def geometry_metadata():
    return {
        'FINAL_STATION_CHORD_PREV_FACTOR': FINAL_STATION_CHORD_PREV_FACTOR,
        'ROOT_INBOARD_EXTENSION_IN': ROOT_INBOARD_EXTENSION_IN,
        'N_BLADES': N_BLADES,
        'HUB_OUTER_DIAMETER_IN': HUB_OUTER_DIAMETER_IN,
        'HUB_THICKNESS_IN': HUB_THICKNESS_IN,
        'M5_CLEARANCE_HOLE_DIAMETER_MM': M5_CLEARANCE_HOLE_DIAMETER_MM,
        'CLEAR_PREVIOUS_BATCH_EXPORTS': CLEAR_PREVIOUS_BATCH_EXPORTS,
        'FAST_SINGLE_RUN_MODE': FAST_SINGLE_RUN_MODE,
        'FAST_SINGLE_RUN_AIRFOIL_POINTS': FAST_SINGLE_RUN_AIRFOIL_POINTS,
        'FAST_SINGLE_RUN_MAX_STATIONS': FAST_SINGLE_RUN_MAX_STATIONS,
        'FAST_SINGLE_RUN_SURFACE_LOFT': FAST_SINGLE_RUN_SURFACE_LOFT
    }


def linspace(n):
    if n < 2:
        return [0.0, 1.0]
    return [i / (n - 1) for i in range(n)]


def smoothstep(t):
    t = max(0.0, min(1.0, t))
    return t * t * (3.0 - 2.0 * t)


# ---------- Math helpers for chord law ----------
def solve_3x3(A, b):
    M = [A[0][:] + [b[0]], A[1][:] + [b[1]], A[2][:] + [b[2]]]
    for col in range(3):
        pivot = col
        for r in range(col, 3):
            if abs(M[r][col]) > abs(M[pivot][col]):
                pivot = r
        if abs(M[pivot][col]) < 1e-12:
            raise ValueError("Singular system while solving cubic coefficients.")
        if pivot != col:
            M[col], M[pivot] = M[pivot], M[col]
        piv = M[col][col]
        for c in range(col, 4):
            M[col][c] /= piv
        for r in range(col + 1, 3):
            factor = M[r][col]
            for c in range(col, 4):
                M[r][c] -= factor * M[col][c]
    x = [0.0, 0.0, 0.0]
    for r in reversed(range(3)):
        x[r] = M[r][3] - sum(M[r][c] * x[c] for c in range(r + 1, 3))
    return x


def cubic_coeffs_with_peak(Croot, Cpeak, Ctip, s_peak):
    """
    chord(s)=a s^3 + b s^2 + c s + d with:
      chord(0)=Croot
      chord(s_peak)=Cpeak
      chord'(s_peak)=0
      chord(1)=Ctip
    all in cm
    """
    if not (0.0 < s_peak < 1.0):
        raise ValueError("ChordPeakS must be between 0 and 1.")
    d = Croot
    sp = s_peak
    A = [
        [1.0, 1.0, 1.0],
        [sp**3, sp**2, sp],
        [3.0 * sp**2, 2.0 * sp, 1.0],
    ]
    bvec = [Ctip - d, Cpeak - d, 0.0]
    a, b, c = solve_3x3(A, bvec)
    return a, b, c, d


def chord_cubic(s, a, b, c, d):
    return a * s**3 + b * s**2 + c * s + d


# ---------- Thickness scaling near root ----------
def thickness_scale_at_s(s, root_scale, end_s, expn):
    end_s = max(1e-6, min(1.0, end_s))
    if s >= end_s:
        return 1.0
    t = s / end_s
    w = smoothstep(t)
    w = w ** max(1.0, expn)
    return (1.0 - w) * root_scale + w * 1.0


# ---------- Tip shaping helpers ----------
def tip_multiplier(s, start_s, end_mult, expn):
    start_s = max(0.0, min(0.999999, start_s))
    if s <= start_s:
        return 1.0
    t = (s - start_s) / (1.0 - start_s)
    w = smoothstep(t)
    w = w ** max(1.0, expn)
    return (1.0 - w) * 1.0 + w * end_mult


def tip_weight(s, start_s, expn):
    start_s = max(0.0, min(0.999999, start_s))
    if s <= start_s:
        return 0.0
    t = (s - start_s) / (1.0 - start_s)
    w = smoothstep(t)
    w = w ** max(1.0, expn)
    return w


def find_le_te_norm_points(airfoil_pts):
    xs = [p[0] for p in airfoil_pts]
    minx = min(xs)
    maxx = max(xs)

    le_candidates = [p for p in airfoil_pts if abs(p[0] - minx) <= X_TOL]
    te_candidates = [p for p in airfoil_pts if abs(p[0] - maxx) <= X_TOL]

    if not le_candidates:
        le_candidates = [min(airfoil_pts, key=lambda p: p[0])]
    if not te_candidates:
        te_candidates = [max(airfoil_pts, key=lambda p: p[0])]

    le_y = sum(p[1] for p in le_candidates) / len(le_candidates)
    te_y = sum(p[1] for p in te_candidates) / len(te_candidates)

    return (minx, le_y), (maxx, te_y)


def close_profile_if_needed(sketch, pts_coll):
    if pts_coll.count < 3:
        return
    p0 = pts_coll.item(0)
    pN = pts_coll.item(pts_coll.count - 1)
    sketch.sketchCurves.sketchLines.addByTwoPoints(pN, p0)


def pick_primary_profile(sketch):
    if sketch.profiles.count == 0:
        return None
    best = sketch.profiles.item(0)
    best_area = abs(best.areaProperties().area)
    for i in range(1, sketch.profiles.count):
        p = sketch.profiles.item(i)
        a = abs(p.areaProperties().area)
        if a > best_area:
            best = p
            best_area = a
    return best


def make_3d_rail_sketch(comp, name):
    sk = comp.sketches.add(comp.xYConstructionPlane)
    sk.is3D = True
    sk.name = name
    return sk


def add_3d_fitted_spline(sketch3d, model_points):
    pts = adsk.core.ObjectCollection.create()
    for p in model_points:
        pts.add(p)
    return sketch3d.sketchCurves.sketchFittedSplines.add(pts)


# ---------- Batch / parameter helpers ----------
def script_dir():
    try:
        return os.path.dirname(os.path.abspath(__file__))
    except:
        return os.getcwd()


def safe_filename(name):
    cleaned = re.sub(r'[^A-Za-z0-9._-]+', '_', str(name).strip().lower())
    return cleaned or 'variant'


def is_angle_parameter(param):
    unit = (getattr(param, 'unit', '') or '').lower()
    return unit in ('deg', 'degree', 'degrees', 'rad', 'radian', 'radians') or param.name.startswith('Twist')


def is_unitless_parameter(param):
    unit = (getattr(param, 'unit', '') or '').lower()
    return unit in ('', 'unitless', 'ul')


def normalize_csv_expression(param, raw_value, variant_id):
    text = str(raw_value).strip()
    if text == '':
        return None

    # Expressions with units/formulas are delegated to Fusion so values like
    # "1.2 in", "3 cm", and "24 deg" keep Fusion's normal unit conversion.
    try:
        num = float(text)
    except:
        return text

    if is_angle_parameter(param):
        return f'{num} deg'
    if is_unitless_parameter(param):
        return str(num)

    # Fusion length parameter .value uses internal centimeters; raw CSV length
    # numbers follow that same convention. Explicit units override this.
    return f'{num} cm'


def validate_parameter_expression(design, param, expression, variant_id):
    units_mgr = design.unitsManager
    try:
        if not units_mgr.isValidExpression(expression, param.unit):
            raise ValueError()
    except Exception as exc:
        label = f'Variant "{variant_id}" ' if variant_id else ''
        raise ValueError(
            f'{label}parameter "{param.name}" could not be parsed: {expression}'
        ) from exc


def recompute_design(design, variant_id=None):
    try:
        design.computeAll()
    except Exception as exc:
        label = f'Variant "{variant_id}" ' if variant_id else ''
        raise RuntimeError(f'{label}failed while recomputing the Fusion design.') from exc
    try:
        adsk.doEvents()
    except:
        pass


def read_current_parameters(design, names=None):
    if names is None:
        names = required_parameter_names()
    params, missing = require_params(design, names)
    if missing:
        raise ValueError('Missing parameters:\n- ' + '\n- '.join(missing))

    data = {}
    for name in names:
        p = params[name]
        data[name] = {
            'expression': p.expression,
            'value': p.value,
            'unit': p.unit
        }
    return params, data


def snapshot_user_parameter_expressions(design):
    return {p.name: p.expression for p in design.userParameters}


def restore_user_parameter_expressions(design, expressions, variant_id=None):
    for name, expression in expressions.items():
        param = get_param(design, name)
        if not param:
            continue
        try:
            param.expression = expression
        except Exception as exc:
            raise RuntimeError(
                parameter_error('could not restore baseline expression.', name, variant_id)
            ) from exc
    recompute_design(design, variant_id)


def force_fixed_radius(design, variant_id=None):
    radius_param = get_param(design, 'Radius')
    if not radius_param:
        raise ValueError(parameter_error('missing required Fusion parameter.', 'Radius', variant_id))
    try:
        validate_parameter_expression(design, radius_param, FIXED_RADIUS_EXPR, variant_id)
        radius_param.expression = FIXED_RADIUS_EXPR
    except Exception as exc:
        raise ValueError(
            parameter_error(
                f'could not be forced to fixed radius expression "{FIXED_RADIUS_EXPR}".',
                'Radius',
                variant_id
            )
        ) from exc
    recompute_design(design, variant_id)


def update_fusion_parameters_from_dict(design, values, variant_id):
    updated = {}
    for name, raw_value in values.items():
        if name is None:
            continue
        if name == 'variant_id' or str(raw_value).strip() == '':
            continue
        if name in IGNORED_CSV_PARAMETER_NAMES:
            continue
        if name == 'Radius':
            # Radius is controlled by FIXED_RADIUS_EXPR, not by the sweep CSV.
            continue

        param = get_param(design, name)
        if not param:
            raise ValueError(
                f'Variant "{variant_id}" references missing Fusion parameter "{name}".'
            )

        expression = normalize_csv_expression(param, raw_value, variant_id)
        if expression is None:
            continue

        try:
            validate_parameter_expression(design, param, expression, variant_id)
            param.expression = expression
            updated[name] = expression
        except Exception as exc:
            raise ValueError(
                f'Variant "{variant_id}" parameter "{name}" could not be assigned from CSV value "{raw_value}" '
                f'as Fusion expression "{expression}".'
            ) from exc
    recompute_design(design, variant_id)
    return updated


def read_variants_csv(path):
    with open(path, 'r', newline='') as f:
        rows = list(csv.DictReader(f))
    if not rows:
        raise ValueError('variants.csv is empty.')
    if 'variant_id' not in (rows[0].keys() if rows else []):
        raise ValueError('variants.csv must include a required "variant_id" column.')
    return rows


def clear_previous_batch_exports(export_dir, variants):
    if not CLEAR_PREVIOUS_BATCH_EXPORTS:
        return []

    deleted = []
    targets = set()
    for row in variants:
        variant_id = str(row.get('variant_id', '')).strip()
        if not variant_id:
            continue
        base_name = safe_filename(variant_id)
        targets.add(base_name + '.stl')
        targets.add(base_name + '.json')

    targets.add('airfoil_blend_debug.csv')

    for filename in sorted(targets):
        path = os.path.join(export_dir, filename)
        if not os.path.isfile(path):
            continue
        try:
            os.remove(path)
            deleted.append(path)
        except Exception as exc:
            raise RuntimeError(f'Could not delete previous batch export "{path}": {exc}') from exc
    return deleted


def write_metadata_json(
    path,
    variant_id,
    parameter_data,
    csv_values,
    twist_metadata=None,
    airfoil_info=None,
    geometry_info=None
):
    metadata = {
        'variant_id': variant_id,
        'TWIST_MODE': TWIST_MODE,
        'parameters': parameter_data,
        'csv_values': csv_values
    }
    if twist_metadata:
        metadata.update(twist_metadata)
    if airfoil_info:
        metadata['airfoils'] = airfoil_info
    if geometry_info:
        metadata['geometry'] = geometry_info
    with open(path, 'w') as f:
        json.dump(metadata, f, indent=2, sort_keys=True)


def find_blade_body(comp, variant_id=None):
    preferred_names = []
    if variant_id:
        preferred_names.append(generated_prop_body_name(variant_id))
        preferred_names.append(generated_blade_body_name(variant_id))
    preferred_names.append(GENERATED_PROP_BASE_NAME)
    preferred_names.append(GENERATED_BLADE_BASE_NAME)
    preferred_names.append('BladeBody')

    for preferred_name in preferred_names:
        for i in range(comp.bRepBodies.count):
            body = comp.bRepBodies.item(i)
            if body.name == preferred_name:
                return body

    for i in range(comp.bRepBodies.count):
        body = comp.bRepBodies.item(i)
        if is_generated_body_name(body.name):
            return body

    for i in range(comp.features.loftFeatures.count):
        feat = comp.features.loftFeatures.item(i)
        if feat.name.startswith('BladeLoft') or feat.name.startswith(GENERATED_BLADE_BASE_NAME):
            for j in range(feat.bodies.count):
                return feat.bodies.item(j)
    return None


def make_hub_body(comp):
    outer_radius_cm = 0.5 * inch_to_cm(HUB_OUTER_DIAMETER_IN)
    hole_radius_cm = 0.5 * mm_to_cm(M5_CLEARANCE_HOLE_DIAMETER_MM)
    thickness_cm = inch_to_cm(HUB_THICKNESS_IN)

    planes = comp.constructionPlanes
    pinput = planes.createInput()
    pinput.setByOffset(comp.xYConstructionPlane, adsk.core.ValueInput.createByReal(-0.5 * thickness_cm))
    plane = planes.add(pinput)
    plane.name = 'Plane_Hub_Start'

    sk = comp.sketches.add(plane)
    sk.name = 'Hub_M5_Clearance'
    center = adsk.core.Point3D.create(0.0, 0.0, 0.0)
    sk.sketchCurves.sketchCircles.addByCenterRadius(center, outer_radius_cm)
    sk.sketchCurves.sketchCircles.addByCenterRadius(center, hole_radius_cm)

    if sk.profiles.count == 0:
        raise RuntimeError('Hub sketch did not create a valid annular profile.')

    hub_profile = pick_primary_profile(sk)
    ext_input = comp.features.extrudeFeatures.createInput(
        hub_profile,
        adsk.fusion.FeatureOperations.NewBodyFeatureOperation
    )
    ext_input.setDistanceExtent(False, adsk.core.ValueInput.createByReal(thickness_cm))
    ext = comp.features.extrudeFeatures.add(ext_input)
    ext.name = GENERATED_HUB_BASE_NAME

    if ext.bodies.count == 0:
        raise RuntimeError('Hub extrusion did not create a body.')
    hub_body = ext.bodies.item(0)
    hub_body.name = GENERATED_HUB_BASE_NAME
    return hub_body


def make_three_blade_pattern(comp, blade_body):
    bodies = [blade_body]
    if N_BLADES <= 1:
        return bodies

    entities = adsk.core.ObjectCollection.create()
    entities.add(blade_body)
    pattern_input = comp.features.circularPatternFeatures.createInput(
        entities,
        comp.zConstructionAxis
    )
    pattern_input.quantity = adsk.core.ValueInput.createByReal(int(N_BLADES))
    pattern_input.totalAngle = adsk.core.ValueInput.createByString('360 deg')

    pattern = comp.features.circularPatternFeatures.add(pattern_input)
    pattern.name = GENERATED_BLADE_BASE_NAME + '_CircularPattern'

    try:
        for i in range(pattern.bodies.count):
            body = pattern.bodies.item(i)
            if body and body.isValid and body not in bodies:
                body.name = f'{GENERATED_BLADE_BASE_NAME}_{i + 2}'
                bodies.append(body)
    except:
        pass
    return bodies


def combine_generated_prop(comp, hub_body, blade_bodies):
    if not hub_body or not hub_body.isValid:
        return None

    tools = adsk.core.ObjectCollection.create()
    for body in blade_bodies:
        if body and body.isValid and body != hub_body:
            tools.add(body)

    if tools.count == 0:
        hub_body.name = GENERATED_PROP_BASE_NAME
        return hub_body

    try:
        combine_input = comp.features.combineFeatures.createInput(hub_body, tools)
        combine_input.operation = adsk.fusion.FeatureOperations.JoinFeatureOperation
        combine_input.isKeepToolBodies = False
        combine = comp.features.combineFeatures.add(combine_input)
        combine.name = GENERATED_PROP_BASE_NAME + '_Join'
        hub_body.name = GENERATED_PROP_BASE_NAME
        return hub_body
    except:
        return None


def export_stl(design, body, path, variant_id=None, comp=None, force_component_export=False):
    try:
        adsk.doEvents()
    except:
        pass
    if force_component_export and comp:
        export_mgr = design.exportManager
        opts = export_mgr.createSTLExportOptions(comp, path)
        try:
            opts.meshRefinement = adsk.fusion.MeshRefinementSettings.MeshRefinementMedium
        except:
            pass
        if not export_mgr.execute(opts):
            label = f'Variant "{variant_id}" ' if variant_id else ''
            raise RuntimeError(f'{label}Fusion STL export failed: {path}')
        return

    if (not body or not body.isValid) and comp:
        body = find_blade_body(comp, variant_id)
    if not body or not body.isValid:
        label = f'Variant "{variant_id}" ' if variant_id else ''
        raise RuntimeError(f'{label}generated blade body is not valid for STL export.')
    export_mgr = design.exportManager
    opts = export_mgr.createSTLExportOptions(body, path)
    try:
        opts.meshRefinement = adsk.fusion.MeshRefinementSettings.MeshRefinementMedium
    except:
        pass
    if not export_mgr.execute(opts):
        label = f'Variant "{variant_id}" ' if variant_id else ''
        raise RuntimeError(f'{label}Fusion STL export failed: {path}')


def show_progress(ui, message):
    try:
        ui.palettes.itemById('TextCommands').writeText(message)
    except:
        pass


def parameter_error(message, parameter_name=None, variant_id=None):
    pieces = []
    if variant_id:
        pieces.append(f'Variant "{variant_id}"')
    if parameter_name:
        pieces.append(f'parameter "{parameter_name}"')
    if pieces:
        return ' '.join(pieces) + f': {message}'
    return message


def twist_deg_at_station(s, x_cm, params, variant_id=None):
    if TWIST_MODE == "linear":
        twist_root_deg = math.degrees(params['TwistRoot'].value)
        twist_tip_deg = math.degrees(params['TwistTip'].value)
        return twist_root_deg + (twist_tip_deg - twist_root_deg) * s

    if TWIST_MODE == "pitch_based":
        if x_cm <= MIN_TWIST_RADIUS_CM:
            raise ValueError(
                parameter_error(
                    'local radius is too close to zero for pitch-based twist.',
                    'HubR',
                    variant_id
                )
            )

        # GeometricPitch is an axial advance distance per revolution. Fusion
        # stores this length parameter in centimeters internally, matching x_cm.
        # The local blade angle beta is in degrees. For constant pitch, beta is
        # large near the hub and decreases toward the tip because each revolution
        # travels a larger circumference at larger radius.
        pitch_cm = params['GeometricPitch'].value
        if pitch_cm <= 0:
            raise ValueError(parameter_error('must be > 0.', 'GeometricPitch', variant_id))
        beta_rad = math.atan(pitch_cm / (2.0 * math.pi * x_cm))
        return math.degrees(beta_rad)

    raise ValueError(f'Unsupported TWIST_MODE "{TWIST_MODE}". Use "linear" or "pitch_based".')


def pitch_based_metadata(params, radius_cm, hub_radius_cm, variant_id=None):
    metadata = {'TWIST_MODE': TWIST_MODE}
    if TWIST_MODE != "pitch_based":
        return metadata

    pitch_cm = params['GeometricPitch'].value
    diameter_cm = 2.0 * radius_cm
    metadata['GeometricPitch'] = {
        'expression': params['GeometricPitch'].expression,
        'value_cm': pitch_cm,
        'unit': params['GeometricPitch'].unit
    }
    metadata['pitch_to_diameter_ratio'] = pitch_cm / diameter_cm if diameter_cm > 0 else None
    metadata['root_blade_angle_deg'] = twist_deg_at_station(0.0, hub_radius_cm, params, variant_id)
    metadata['tip_blade_angle_deg'] = twist_deg_at_station(1.0, radius_cm, params, variant_id)
    return metadata


def generate_blade_geometry(design, airfoil_set, variant_id=None):
    params, _ = read_current_parameters(design)
    root_airfoil = airfoil_set['root_pts']
    mid_airfoil = airfoil_set['mid_pts']
    tip_airfoil = airfoil_set['tip_pts']

    # LENGTHS: Fusion .value is cm
    Radius_cm = params['Radius'].value
    HubR_param_cm = params['HubR'].value
    HubR_cm = HubR_param_cm - inch_to_cm(ROOT_INBOARD_EXTENSION_IN)

    ChordRoot_cm = params['ChordRoot'].value
    ChordPeak_cm = params['ChordPeak'].value
    ChordTip_cm = params['ChordTip'].value

    TipTEOffset_cm = params['TipTEOffset'].value

    # UNITLESS
    s_peak = float(params['ChordPeakS'].value)

    ThickRootScale = float(params['ThickRootScale'].value)
    ThickEndS = float(params['ThickEndS'].value)
    ThickExp = float(params['ThickExp'].value)

    TipShapeStartS = float(params['TipShapeStartS'].value)
    TipShapeExp = float(params['TipShapeExp'].value)
    TipThickScale = float(params['TipThickScale'].value)

    TipTEOffsetStartS = float(params['TipTEOffsetStartS'].value)
    TipTEOffsetExp = float(params['TipTEOffsetExp'].value)

    # COUNTS
    nStations = int(round(params['nStations'].value))
    if nStations < 2:
        nStations = 2
    requested_nStations = nStations
    if is_fast_single_run():
        nStations = min(nStations, max(3, int(FAST_SINGLE_RUN_MAX_STATIONS)))

    Span_cm = Radius_cm - HubR_cm
    if Span_cm <= 0:
        raise ValueError(
            parameter_error(
                f'Radius must be greater than HubR minus ROOT_INBOARD_EXTENSION_IN ({ROOT_INBOARD_EXTENSION_IN} in).',
                'Radius',
                variant_id
            )
        )
    if TWIST_MODE == "pitch_based":
        if HubR_cm <= MIN_TWIST_RADIUS_CM:
            raise ValueError(
                parameter_error(
                    f'minus ROOT_INBOARD_EXTENSION_IN ({ROOT_INBOARD_EXTENSION_IN} in) must stay greater than zero for pitch-based twist.',
                    'HubR',
                    variant_id
                )
            )

    # Validation (minimal)
    if not (0.0 < s_peak < 1.0):
        raise ValueError(parameter_error('must be between 0 and 1.', 'ChordPeakS', variant_id))
    if not (0.0 < FINAL_STATION_CHORD_PREV_FACTOR <= 1.0):
        raise ValueError('FINAL_STATION_CHORD_PREV_FACTOR must be > 0 and <= 1.')
    if TipTEOffset_cm < 0:
        raise ValueError(parameter_error('must be >= 0.', 'TipTEOffset', variant_id))

    # Cubic chord law (cm)
    a, b, c, d = cubic_coeffs_with_peak(ChordRoot_cm, ChordPeak_cm, ChordTip_cm, s_peak)

    # Component
    comp = ensure_component(design, 'AirfoilSections')
    delete_old(comp)

    # Planes along +X using YZ base plane
    base_plane = comp.yZConstructionPlane
    planes = comp.constructionPlanes
    pinput = planes.createInput()

    # Base rotation in sketch plane
    base_theta = math.radians(BASE_ROT_DEG)
    cb, sb = math.cos(base_theta), math.sin(base_theta)

    section_profiles = []
    le_model_points = []
    te_model_points = []

    s_list = linspace(nStations)
    chord_by_station = [max(chord_cubic(s, a, b, c, d), 1e-6) for s in s_list]
    if len(chord_by_station) >= 2:
        chord_by_station[-1] = max(
            chord_by_station[-2] * FINAL_STATION_CHORD_PREV_FACTOR,
            1e-6
        )

    for i, s in enumerate(s_list):
        station_airfoil = airfoil_for_station(s, root_airfoil, mid_airfoil, tip_airfoil)
        le_norm, te_norm = find_le_te_norm_points(station_airfoil)

        # ABSOLUTE placement: root at HubR, tip at Radius
        x_cm = HubR_cm + (Radius_cm - HubR_cm) * s

        # Chord path is intentionally simple:
        # - stations up to the second-to-last follow only the cubic
        #   ChordRoot/ChordPeak/ChordTip law
        # - the final station is a fixed fraction of the second-to-last chord
        Chord_cm = chord_by_station[i]

        # Root thickness scaling * tip thinning
        t_root = thickness_scale_at_s(s, ThickRootScale, ThickEndS, ThickExp)
        t_tip = tip_multiplier(s, TipShapeStartS, TipThickScale, TipShapeExp)
        t_scale = t_root * t_tip

        # Twist:
        # - linear mode interpolates blade angle in degrees between TwistRoot and TwistTip.
        # - pitch_based mode uses geometric pitch length to compute local blade angle:
        #   beta(r)=atan(P/(2*pi*r)), with P and r both in centimeters.
        twist_deg = twist_deg_at_station(s, x_cm, params, variant_id)
        twist_theta = -math.radians(twist_deg) if INVERT_TWIST else math.radians(twist_deg)
        ct, st = math.cos(twist_theta), math.sin(twist_theta)

        # Create plane at x_cm
        pinput.setByOffset(base_plane, adsk.core.ValueInput.createByReal(x_cm))
        plane = planes.add(pinput)
        plane.name = f'Plane_s={s:.3f}'

        # Sketch on plane
        sk = comp.sketches.add(plane)
        sk.name = f'AF_s={s:.3f}'

        # Center profile to origin (bbox center in sketch space)
        if CENTER_TO_ORIGIN:
            xs = [x * Chord_cm for (x, y) in station_airfoil]
            ys = [(y * Chord_cm) * t_scale for (x, y) in station_airfoil]
            cx0 = 0.5 * (min(xs) + max(xs))
            cy0 = 0.5 * (min(ys) + max(ys))
        else:
            cx0 = cy0 = 0.0

        # --- Tip TE-offset: compute chord direction (LE->TE) in sketch coords, then offset ---
        w_off = tip_weight(s, TipTEOffsetStartS, TipTEOffsetExp)
        off_cm = w_off * TipTEOffset_cm

        def transformed_xy_no_offset(norm_xy):
            xn, yn = norm_xy
            px = xn * Chord_cm - cx0
            py = (yn * Chord_cm) * t_scale - cy0

            bx = px * cb - py * sb
            by = px * sb + py * cb

            rx = bx * ct - by * st
            ry = bx * st + by * ct
            return rx, ry

        le_rx, le_ry = transformed_xy_no_offset(le_norm)
        te_rx, te_ry = transformed_xy_no_offset(te_norm)

        vx, vy = (te_rx - le_rx), (te_ry - le_ry)
        vlen2 = vx * vx + vy * vy
        if vlen2 < 1e-12:
            ux, uy = 1.0, 0.0
        else:
            vlen = math.sqrt(vlen2)
            ux, uy = vx / vlen, vy / vlen

        dx, dy = off_cm * ux, off_cm * uy

        # Build the section curve points in sketch coords (cm), WITH TE offset
        pts = adsk.core.ObjectCollection.create()
        for x_norm, y_norm in station_airfoil:
            px = x_norm * Chord_cm - cx0
            py = (y_norm * Chord_cm) * t_scale - cy0

            bx = px * cb - py * sb
            by = px * sb + py * cb

            rx = bx * ct - by * st
            ry = bx * st + by * ct

            pts.add(adsk.core.Point3D.create(rx + dx, ry + dy, 0.0))

        sk.sketchCurves.sketchFittedSplines.add(pts)
        close_profile_if_needed(sk, pts)

        prof = pick_primary_profile(sk)
        if prof:
            section_profiles.append(prof)

        # LE/TE points for rails (apply same dx/dy)
        le_sk_pt = adsk.core.Point3D.create(le_rx + dx, le_ry + dy, 0.0)
        te_sk_pt = adsk.core.Point3D.create(te_rx + dx, te_ry + dy, 0.0)

        le_model_points.append(sk.sketchToModelSpace(le_sk_pt))
        te_model_points.append(sk.sketchToModelSpace(te_sk_pt))

    # Create rails in 3D sketch
    rails_sk = make_3d_rail_sketch(comp, 'Rails_LE_TE')
    le_spline = add_3d_fitted_spline(rails_sk, le_model_points)
    te_spline = add_3d_fitted_spline(rails_sk, te_model_points)

    # Loft
    loft_msg = ""
    blade_body = None
    if CREATE_LOFT:
        try:
            loftFeats = comp.features.loftFeatures
            op = adsk.fusion.FeatureOperations.NewBodyFeatureOperation
            loftInput = loftFeats.createInput(op)

            loftInput.isSolid = active_make_solid_loft()

            for prof in section_profiles:
                loftInput.loftSections.add(prof)

            loftInput.centerLineOrRails.addRail(le_spline)
            loftInput.centerLineOrRails.addRail(te_spline)

            loft = loftFeats.add(loftInput)
            loft.name = 'BladeLoft'
            try:
                adsk.doEvents()
            except:
                pass
            if loft.bodies.count > 0:
                blade_body = loft.bodies.item(0)
                blade_body.name = generated_blade_body_name()
            else:
                blade_body = find_blade_body(comp)
            loft_msg = "Loft: created (BladeLoft)."
        except:
            loft_msg = "Loft: FAILED (sections+rails still created).\n" + traceback.format_exc()

    if blade_body and blade_body.isValid:
        blade_body.name = generated_blade_body_name()
    else:
        blade_body = find_blade_body(comp)

    prop_body = None
    generated_body_count = 1 if blade_body and blade_body.isValid else 0
    if blade_body and blade_body.isValid and active_make_solid_loft():
        try:
            blade_bodies = make_three_blade_pattern(comp, blade_body)
            hub_body = make_hub_body(comp)
            generated_body_count = len([b for b in blade_bodies if b and b.isValid]) + (1 if hub_body and hub_body.isValid else 0)
            prop_body = combine_generated_prop(comp, hub_body, blade_bodies)
            if prop_body and prop_body.isValid:
                generated_body_count = 1
                blade_body = prop_body
                loft_msg += f'\nProp assembly: {N_BLADES} blades + hub created and joined.'
            else:
                loft_msg += f'\nProp assembly: {N_BLADES} blades + hub created; join skipped or failed.'
        except:
            loft_msg += '\nProp assembly: FAILED.\n' + traceback.format_exc()

    return {
        'airfoil_name': airfoil_set['display_name'],
        'airfoil_metadata': airfoil_metadata(airfoil_set),
        'sections_found': len(section_profiles),
        'requested_stations': requested_nStations,
        'stations_used': nStations,
        'airfoil_points_used': active_airfoil_point_count(),
        'fast_single_run': is_fast_single_run(),
        'solid_loft': active_make_solid_loft(),
        'hub_radius_cm': HubR_cm,
        'hub_radius_parameter_cm': HubR_param_cm,
        'root_inboard_extension_in': ROOT_INBOARD_EXTENSION_IN,
        'radius_cm': Radius_cm,
        'twist_metadata': pitch_based_metadata(params, Radius_cm, HubR_cm, variant_id),
        'loft_msg': loft_msg,
        'body': blade_body,
        'component': comp,
        'generated_body_count': generated_body_count
    }


def select_airfoil_dat(ui, label='airfoil'):
    dlg = ui.createFileDialog()
    dlg.title = f'Select {label} Selig-format airfoil .dat'
    dlg.filter = 'DAT files (*.dat)'
    if dlg.showOpen() != adsk.core.DialogResults.DialogOK:
        return None
    return dlg.filename


def load_resampled_airfoil(path, label):
    try:
        name, pts = read_selig_dat(path)
    except Exception as exc:
        raise ValueError(f'Failed to load {label} airfoil file:\n{path}\n{exc}') from exc
    try:
        resampled = resample_airfoil_loop(pts, active_airfoil_point_count())
    except Exception as exc:
        raise ValueError(f'Failed to resample {label} airfoil "{name}" from:\n{path}\n{exc}') from exc
    return name, resampled


def load_airfoil_set(ui):
    validate_airfoil_transition_ranges()

    paths = {
        'root': RootAirfoilPath,
        'mid': MidAirfoilPath,
        'tip': TipAirfoilPath
    }
    labels = {
        'root': 'root/thick',
        'mid': 'mid-span',
        'tip': 'tip/thin'
    }

    for key in ('root', 'mid', 'tip'):
        if not paths[key]:
            path = select_airfoil_dat(ui, labels[key])
            if not path:
                return None
            paths[key] = path

    root_name, root_pts = load_resampled_airfoil(paths['root'], 'root')
    mid_name, mid_pts = load_resampled_airfoil(paths['mid'], 'mid')
    tip_name, tip_pts = load_resampled_airfoil(paths['tip'], 'tip')

    return {
        'root_path': paths['root'],
        'mid_path': paths['mid'],
        'tip_path': paths['tip'],
        'root_name': root_name,
        'mid_name': mid_name,
        'tip_name': tip_name,
        'root_pts': root_pts,
        'mid_pts': mid_pts,
        'tip_pts': tip_pts,
        'display_name': f'Root: {root_name} | Mid: {mid_name} | Tip: {tip_name}'
    }


def export_airfoil_debug_csv(output_dir, airfoil_set):
    if not EXPORT_AIRFOIL_DEBUG_CSV:
        return None
    if not os.path.isdir(output_dir):
        os.makedirs(output_dir)
    path = os.path.join(output_dir, 'airfoil_blend_debug.csv')
    debug_stations = [0.0, 0.3, 0.5, 0.75, 1.0]
    with open(path, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['s', 'point_index', 'x_norm', 'y_norm'])
        for s in debug_stations:
            pts = airfoil_for_station(
                s,
                airfoil_set['root_pts'],
                airfoil_set['mid_pts'],
                airfoil_set['tip_pts']
            )
            for idx, (x, y) in enumerate(pts):
                writer.writerow([s, idx, x, y])
    return path


def select_variants_csv(ui):
    dlg = ui.createFileDialog()
    dlg.title = 'Select variants.csv (Cancel for single run)'
    dlg.filter = 'CSV files (*.csv)'
    default_path = os.path.join(script_dir(), VARIANTS_CSV_NAME)
    if os.path.exists(default_path):
        try:
            dlg.initialDirectory = script_dir()
            dlg.filename = default_path
        except:
            pass
    if dlg.showOpen() != adsk.core.DialogResults.DialogOK:
        return None
    return dlg.filename


def run_single_variant(ui, design, airfoil_set):
    force_fixed_radius(design)
    result = generate_blade_geometry(design, airfoil_set)
    debug_path = export_airfoil_debug_csv(script_dir(), airfoil_set)
    debug_msg = f'\nAirfoil debug CSV:\n{debug_path}' if debug_path else ''
    ui.messageBox(
        f'Airfoils:\n{result["airfoil_name"]}\n'
        f'Radius fixed at: {FIXED_RADIUS_EXPR}\n'
        f'Twist mode: {TWIST_MODE}\n'
        f'Fast single-run preview: {result["fast_single_run"]}\n'
        f'Airfoil points per station: {result["airfoil_points_used"]}\n'
        f'Stations used: {result["stations_used"]} of requested {result["requested_stations"]}\n'
        f'Solid loft: {result["solid_loft"]}\n'
        f'Sections (profiles found): {result["sections_found"]}\n'
        f'Root X after inboard extension (cm): {result["hub_radius_cm"]:.3f}\n'
        f'Tip X should equal Radius (cm): {result["radius_cm"]:.3f}\n'
        f'Final station chord factor: {FINAL_STATION_CHORD_PREV_FACTOR:.3f} of previous station\n'
        f'Root moved inboard: {ROOT_INBOARD_EXTENSION_IN:.3f} in\n'
        f'Blade count: {N_BLADES}; hub OD: {HUB_OUTER_DIAMETER_IN:.3f} in; hole: {M5_CLEARANCE_HOLE_DIAMETER_MM:.1f} mm\n'
        f'{result["loft_msg"]}'
        f'{debug_msg}'
    )


def run_batch_variants(ui, design, airfoil_set, csv_path):
    variants = read_variants_csv(csv_path)
    export_dir = os.path.join(os.path.dirname(csv_path), EXPORTS_DIR_NAME)
    if not os.path.isdir(export_dir):
        os.makedirs(export_dir)
    deleted_exports = clear_previous_batch_exports(export_dir, variants)
    debug_path = export_airfoil_debug_csv(export_dir, airfoil_set)
    baseline_expressions = snapshot_user_parameter_expressions(design)

    succeeded = 0
    failed = 0
    failures = []

    # Batch workflow:
    # 1. Read one CSV row.
    # 2. Push matching CSV columns into Fusion user parameters.
    # 3. Rebuild the same section/rail/loft geometry.
    # 4. Export STL and write JSON metadata beside it.
    for index, row in enumerate(variants, start=1):
        variant_id = str(row.get('variant_id', '')).strip()
        if not variant_id:
            failed += 1
            failures.append(f'Row {index}: missing variant_id')
            continue

        show_progress(ui, f'Generating variant {index}/{len(variants)}: {variant_id}')
        try:
            restore_user_parameter_expressions(design, baseline_expressions, variant_id)
            force_fixed_radius(design, variant_id)
            update_fusion_parameters_from_dict(design, row, variant_id)
            force_fixed_radius(design, variant_id)
            result = generate_blade_geometry(design, airfoil_set, variant_id)
            recompute_design(design, variant_id)
            body = result['body']
            if (not body or not body.isValid) and result.get('component'):
                body = find_blade_body(result['component'], variant_id)
            if not body or not body.isValid:
                raise RuntimeError(result['loft_msg'] or 'No blade body was created.')
            body.name = generated_prop_body_name(variant_id)

            _, parameter_data = read_current_parameters(design)
            base_name = safe_filename(variant_id)
            stl_path = os.path.join(export_dir, base_name + '.stl')
            json_path = os.path.join(export_dir, base_name + '.json')

            export_stl(
                design,
                body,
                stl_path,
                variant_id,
                result.get('component'),
                result.get('generated_body_count', 1) > 1
            )
            write_metadata_json(
                json_path,
                variant_id,
                parameter_data,
                row,
                result.get('twist_metadata'),
                result.get('airfoil_metadata'),
                geometry_metadata()
            )
            succeeded += 1
        except Exception as exc:
            failed += 1
            failures.append(f'{variant_id}: {exc}')
            show_progress(ui, f'FAILED variant {variant_id}: {exc}')

    summary = (
        f'Batch complete.\n'
        f'Radius fixed at {FIXED_RADIUS_EXPR} for all variants.\n'
        f'Twist mode: {TWIST_MODE}\n'
        f'Previous batch exports deleted: {len(deleted_exports)}\n'
        f'Variants successfully exported: {succeeded}\n'
        f'Failed: {failed}\n'
        f'Exports folder:\n{export_dir}'
    )
    if debug_path:
        summary += f'\nAirfoil debug CSV:\n{debug_path}'
    if failures:
        summary += '\n\nFailures:\n- ' + '\n- '.join(failures[:10])
        if len(failures) > 10:
            summary += f'\n- ...and {len(failures) - 10} more.'
    ui.messageBox(summary)


# ---------- Command ----------
class ExecuteHandler(adsk.core.CommandEventHandler):
    def notify(self, args):
        app = adsk.core.Application.get()
        ui = app.userInterface
        try:
            design = adsk.fusion.Design.cast(app.activeProduct)
            if not design:
                ui.messageBox('No active design.')
                return

            airfoil_set = load_airfoil_set(ui)
            if not airfoil_set:
                return

            # Validate the base design once before either single-run or batch.
            read_current_parameters(design)

            csv_path = None
            if BATCH_MODE:
                csv_path = select_variants_csv(ui)

            if csv_path:
                run_batch_variants(ui, design, airfoil_set, csv_path)
            else:
                run_single_variant(ui, design, airfoil_set)

        except:
            ui.messageBox(traceback.format_exc())


class CreatedHandler(adsk.core.CommandCreatedEventHandler):
    def notify(self, args):
        h = ExecuteHandler()
        args.command.execute.add(h)
        _handlers.append(h)


def run(context):
    app = adsk.core.Application.get()
    ui = app.userInterface
    cmd = ui.commandDefinitions.itemById(CMD_ID)
    if cmd:
        cmd.deleteMe()
    cmd = ui.commandDefinitions.addButtonDefinition(CMD_ID, CMD_NAME, CMD_DESC)
    h = CreatedHandler()
    cmd.commandCreated.add(h)
    _handlers.append(h)
    cmd.execute()
    adsk.autoTerminate(False)


def stop(context):
    app = adsk.core.Application.get()
    ui = app.userInterface
    cmd = ui.commandDefinitions.itemById(CMD_ID)
    if cmd:
        cmd.deleteMe()
